title: "Tennis Actus"
description: "Toute la passion du tennis en un seul site : news, classements et événements."
baseurl: "/tennis-actus"
url: "https://tonpseudo.github.io"  # remplace ici par ton identifiant GitHub
theme: minimal-mistakes-jekyll
